# Site settings
baseurl = "https://rotaract-club.netlify.com/"
languageCode = "fr"
title = "Rotaract Club de Blois"

[params]
	name = "Rotaract Club de Blois"
	description = "Association de jeunes étudiants / actifs !"
	email = "Rotaractclubdeblois@gmail.com"
#    gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBbpv1OlJM2fIPSYZhvDjQj_Y6p_WFeCow"
    googleAnalytics = "UA-104679908-1"

	[params.header]
		title = "Rotaract Club de Blois"

	[params.about]
		title = "Le Rotaract Club de Blois"
        devise1 = "Vous présente son engagement, "
		devise2 = "ainsi que ses projets."
		devise3 = "Le Rotaract renaît !"
		bio = "Le Rotaract est un club service parrainé par le Rotary. Cette association jeunesse regroupe des jeunes entre 18 et 30 ans. Le Rotaract se réunit pour mettre en place des actions de solidarités."
#		bio_text_redirect_mail = "Les portes du Rotaract de Blois sont ouvertes à tout le monde !!!"
		bio_redirect_mail = "Vous êtes intéressé ? Motivé ?"
#        bio_titre_devise = "Notre devise : "
        bio_devise = " **« L’AMITIÉ PAR LE SERVICE »** "
        bio_titre_ojbectifs = "Nos Objectifs :"
        bio_objectifs = "Les objectifs des clubs Rotaract consistent à mener des actions d’intérêt public (oeuvrer pour le bien d’autrui), d’actions internationales (développer des actions humanitaires par-delà les frontières, favoriser l’entente internationale (en accueillant par exemple des étudiants étrangers), d’actions intérieures (coordonner des actions d’utilité publique au niveau local), et d’actions professionnelles (organiser des conférences afin de faire partager à tous des expériences dans le domaine professionnel ou culturel)."
        bio_titre_nous_a_blois = "Nous, à Blois :"
        bio_nous_a_blois = "Aujourd’hui Blois est un petit groupe de jeunes professionnels et étudiants réunis pour créer en 2017-2018 une action Hors'Aract, 2019 sera la seconde émission, afin de pouvoir faire des dons à l’I.M.E. du Val de Loire et plein d'autres actions encore."

#    [[params.about.skills]]
#    name = "Communication"
#    value = 9
#
#    [[params.about.skills]]
#    name = "Organization"
#    value = 7
#
#    [[params.about.skills]]
#    name = "Learning"
#    value = 10
#
#    [[params.about.skills]]
#        name = "Teaching"
#        value = 6
#
#    [[params.about.skills]]
#        name = "Planning"
#        value = 7
#
#    [[params.about.skills]]
#        name = "Visual Design"
#        value = 5
#
#    [[params.about.skills]]
#        name = "UX Design"
#        value = 8
#
#    [[params.about.skills]]
#        name = "Programming"
#        value = 6

	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "facebook"
			link = "https://www.facebook.com/RotaractBloisOfficiel/"


	[params.form]
		title = "Nous rejoindre !"
		# Form fields
		name = "Nom"
		email = "Email"
		message = "Message"
		buttonText = "Envoyer"


	[params.footer]
		copyright = "© 2019 by Rotaract. All rights reserved."
